language: node_js
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install mongodb-org
  - sudo apt-get install screen
  - screen -d -m mongod
  - npm install -g bower
  - npm install -g grunt-cli
  - gem install sass
install:
  - npm install
  - bower install
  - make place-assets
  - grunt build
script:
  - screen -d -m npm start
  - sleep 10
  - make test
