language: node_js
rvm: ruby-head
gemfile:
  - sass
install:
  - npm install -g bower
  - npm install -g grunt-cli
  - npm install --dev
  - bower install
  - make place-assets
  - grunt build
script:
  - make test
